version: "3"
services:
  app:
    environment:
        - NODE_ENV=development
    command: dev
    volumes:
        - ./src:/usr/src/app
        - /usr/src/app/node_modules
        - /usr/src/app/.next
